<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="2DI3052" name="tests.TC_001_Login_Valid" tests="3" failures="1" timestamp="03 Jan 2020 14:58:56 GMT" time="99.635" errors="0">
  <testcase name="Invalid_Login_Test" time="15.901" classname="tests.TC_001_Login_Valid">
    <failure type="java.lang.AssertionError" message="expected [Incorrect Username/Password] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect Username/Password] but found [Test]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.Login.Verify_Error_Msg(Login.java:65)
at tests.TC_001_Login_Valid.Invalid_Login_Test(TC_001_Login_Valid.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Invalid_Login_Test -->
  <testcase name="Invalid_Login_Test" time="38.847" classname="tests.TC_001_Login_Valid">
    <skipped/>
  </testcase> <!-- Invalid_Login_Test -->
  <testcase name="Valid_Login_Test" time="44.887" classname="tests.TC_001_Login_Valid"/>
</testsuite> <!-- tests.TC_001_Login_Valid -->
